name: gate_access
description: "Gate Access Security App for The Bears"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  provider:
  awesome_dialog: ^3.0.2
  fluttertoast: ^8.0.8
  rounded_loading_button: ^2.1.0

  image_picker: ^0.8.4+4
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21 #

flutter_native_splash:
  color: "#000000"
  image: assets/images/app-logo.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Ubuntu Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
